### ISSUE TITLE
add support for disabling cert verification

### ISSUE THREAD

**Issue by fredless** [WebexCommunity/WebexPythonSDK#138]
related to #133 and for debugging\troubleshooting in general, would be nice to include support for passing `verify=False` through to `requests` to make working with a self-signing SSL sniffer (Fiddler or similar) more easily accomplished.

**Comment by fredless** [comment]
..and in the meantime, one way around this is to simply `import certifi`, ensuring that you add your proxies certificate (in `base64`) to its CA list beforehand to override the list of trusted CAs.  works for most things that use `requests` underneath.

**Comment by sQu4rks** [comment]
Hi @fredless 

thanks for raising this. I just pushed a PR that introduces a `disable_ssl_verify` flag to the rest session and api object.
