### ISSUE TITLE
Address DeprecationWarning

### ISSUE THREAD

**Issue by frvge** [WebexCommunity/WebexPythonSDK#139]
A project that works fine with pytest starts throwing DeprecationWarnings the moment I add `from webexteamssdk import WebexTeamsAPI`

```
venv/lib/python3.8/site-packages/future-0.18.2-py3.8.egg/future/standard_library/__init__.py:65
  /Users/frvge/myproject/venv/lib/python3.8/site-packages/future-0.18.2-py3.8.egg/future/standard_library/__init__.py:65: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

-- Docs: https://docs.pytest.org/en/stable/warnings.html
```

`platform darwin -- Python 3.8.3, pytest-6.0.2, py-1.9.0,`

I guess it's because webexteamssdk imports from __future__ and the future package imports imp.

I'm aware I can suppress these warnings, so this is more meant as a FYI.

Used webexteamssdk>=1.6.0

**Comment by joshjhans** [comment]
Any news on this?

**Comment by Joezanini** [comment]
https://docs.python.org/3/reference/simple_stmts.html#future-statements

**Comment by Joezanini** [comment]
I am going to be making the changes to remove this dependency from the project.
