### ISSUE TITLE
endless loop listing rooms

### ISSUE THREAD

**Issue by fredless** [WebexCommunity/WebexPythonSDK#146]
```python
spaces = api.rooms.list(sortBy='lastactivity')
for space in spaces:
    do_something(space)
```

While code like the above has previously worked without issue against my account, it now loops endlessly; repeating through spaces that are returned near the end to infinity.  If I try to load the whole **GeneratorContainer** all at once - like
```python
spaces = list(api.rooms.list(sortBy='lastactivity')
```
..it similarly just goes on "forever" (in reality, it usually eventually errors out with a 502 or 503 after a very long time).

Now if I leave out `sortBy='lastactivity'` - it works fine, iterating through my ~1000 spaces without issue. I noticed this start a month or two ago, just took me a while to get back to my code and look at the issue.

Anyone else seeing the same?

**Comment by cmlccie** [comment]
Closing this issue as it is more than three years old.

The `GeneratorContainers` in the SDK provide automatic pagination handling for paged responses from the Webex APIs. If the iterator continues forever, it is because the API continues to provide paged results.
