### ISSUE TITLE
Incorrect type

### ISSUE THREAD

**Issue by DanilaCharushin** [WebexCommunity/WebexPythonSDK#153]
https://github.com/CiscoDevNet/webexteamssdk/blob/49a0a0d07d8d7c11abdf599396c814455261cc76/webexteamssdk/api/messages.py#L264

attachments -> attachment, AdaptiveCard expects AdaptiveCard, not a List[AdaptiveCard]

**Comment by cmlccie** [comment]
Fixed 3 years ago:

https://github.com/WebexCommunity/WebexPythonSDK/commit/2bc4c75b31b72d611c531442dd0ff0de5f770938
