### ISSUE TITLE
Send text / markdown with syntax highlighting

### ISSUE THREAD

**Issue by AdrienPensart** [WebexCommunity/WebexPythonSDK#154]
Hello,

do you have an example to send json text with syntax highlighting ?

I tried with : 
`
text = "```json\n{"key": "value"}\n```"
`

or
` 
markdown "```json\n{"key": "value"}\n```"
`

It is printed in a code-block, but without syntax highlighting, it works in heavy client Webex teams.
Or how do you simply colorize a message ?

**Comment by fdemello** [comment]
It doesn't look like this is supported. I even tried sending the same HTML that the desktop client creates when you send code highlighted like `<pre><code class=\"language-json\">{&quot;key&quot;: &quot;value&quot;}\n</code></pre>`.

**Comment by ccondry** [comment]
confirming this issue. I am unable to get syntax highlighting to work for any language when using REST request to send a message.

**Comment by davidstaudt** [comment]
I believe this is a known issue I've reported to the Webex API team previously - you might want to also report it to them directly yourself to help raise visibility/priority (https://developer.webex.com/support)

**Comment by robrez** [comment]
Any updates or workarounds?

**Comment by cmlccie** [comment]
Closing this issue as it is approximately three years old and appears to have been an issue with the Webex APIs and not the Python SDK.
