### ISSUE TITLE
Add Support for Editing a Message

### ISSUE THREAD

**Issue by cpissay** [WebexCommunity/WebexPythonSDK#160]
## Problem
Currently there is no method in the MessagesAPI class which can edit a message .
This is a really useful feature to have to keep the space uncluttered of unnecessary bot messages and that annoying "deleted their message" messages.

## Edit Message API
As per the documentation in [developer.cisco.com](developer.cisco.com), to edit a message, we need to send a HTTP PUT to `/v1/messages/{messageId}` with the following body parameters:
- roomId
- text
- markdown
- attachment (the guide doesn't have this, but I have tested this and it works)

_But editing messages with files are not supported, so file is not an allowed parameter_

## Potential python syntax 
```python
from webexteamssdk import WebexTeamsAPI
api = WebexTeamsAPI()
api.messages.edit(messageId="string", text="string", markdown="string",attachment=[list])
```

**Comment by leighmhart** [comment]
Hi @cpissay, this would definitely be useful and I made a start with [a fork](https://github.com/leighmhart/webexteamssdk/tree/patch-1) but realised when reviewing the [contributing guidelines](https://github.com/CiscoDevNet/webexteamssdk/blob/673312779b8e05cf0535bea8b96599015cccbff1/docs/contributing.rst) that I lack the experience to create a test case.

Additionally, I noted that (as you pointed out) attachments aren't supported (thus cards) but curious that it worked for you - I haven't tried yet... might play around with [Extending the API with bound methods](https://github.com/CiscoDevNet/webexteamssdk/blob/master/docs/user/quickstart.rst#extending-the-api-with-bound-methods) while these issues are addressed...

**Comment by erqiyang** [comment]
yes.. @cpissay is right. The API is working fine. @leighmhart , the response you are getting back from the API is likely because of images in your card (if you are using cards) or other file attachment. Also, the current limit for editing messages is a max of 10 edits. Any more than that, you will also get a 400 Bad Request response.

You can read more about it here:
https://developer.webex.com/docs/api/v1/messages/edit-a-message

**Comment by leighmhart** [comment]
> yes.. @cpissay is right. The API is working fine. @leighmhart , the response you are getting back from the API is likely because of images in your card (if you are using cards) or other file attachment. Also, the current limit for editing messages is a max of 10 edits. Any more than that, you will also get a 400 Bad Request response.
> 
> You can read more about it here: https://developer.webex.com/docs/api/v1/messages/edit-a-message

You are indeed correct - I removed the image reference and edit now works - however, there was one missing piece to the _edit overload function - returning the json message object :)

```
    # Return a message object created from the response JSON data
    return self._object_factory(OBJECT_TYPE, json_data)

```

**Comment by cmlccie** [comment]
Closing this issue; it looks like the functionality was added in #190.
