### ISSUE TITLE
Set a default Greeting/Help message in bot - bot banner

### ISSUE THREAD

**Issue by sML-90** [WebexCommunity/WebexPythonSDK#164]
Hey Team..can anyone suggest me how to setup a greeting/help message in a WebEx bot..I am using webexteamssdk 1.6 to send and retrieve messages from the chat. I could not find option to provide greeting. Any help would be greatly appreciated.

Thanks in advance

**Comment by cmlccie** [comment]
Closing this issue; it is a troubleshooting/assistance request that is almost three years old.
