### ISSUE TITLE
Connection to webexapis.com timed out

### ISSUE THREAD

**Issue by prabhat111** [WebexCommunity/WebexPythonSDK#172]
I tried "webexteamssdk" as python module and got the below error. 
Kindly help me on this.

requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='webexapis.com', port=443): Max retries exceeded with url: /v1/messages (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb8bff30588>, 'Connection to webexapis.com timed out. (connect timeout=60)'))

**Comment by dongwangchn** [comment]
may need http(s)_proxy

**Comment by cmlccie** [comment]
Closing this issue; appears to have been an environment/API-connectivity issue.
