### ISSUE TITLE
Python 3.12, versioneer build failure

### ISSUE THREAD

**Issue by scop** [WebexCommunity/WebexPythonSDK#189]
versioneer.py attempts to use `configparser.SafeConfigParser` which has been [deprecated for a long time, and now removed in Python 3.12](https://github.com/python/cpython/blob/v3.11.1/Lib/configparser.py#L1242-L1252), causing build to fail.

Upgrading versioneer to a newer version would seem likely to fix this: https://github.com/python-versioneer/python-versioneer/issues/200

**Comment by Joezanini** [comment]
Moved to [Poetry Dynamic Versioning](https://pypi.org/project/poetry-dynamic-versioning/) with [V2.0.0 release](https://github.com/WebexCommunity/WebexPythonSDK/releases/tag/v2.0.0)
