### ISSUE TITLE
Support reactions to messages

### ISSUE THREAD

**Issue by claell** [WebexCommunity/WebexPythonSDK#194]
Maybe I haven't looked close enough, but it seems that reactions like thumbs up to a message aren't supported currently?

**Comment by claell** [comment]
Turns out that the API isn't supporting it in the first place as of now: https://community.cisco.com/t5/webex-for-developers/add-message-reactions-like-thumbs-up-through-webex-api/m-p/4822918

**Comment by claell** [comment]
@migueloon Thanks for linking them. However, to me, it looks that this will only provide the retrieval of reactions, not the addition of them?

**Comment by claell** [comment]
I added an idea before, but didn't add it here, back then. Now, it seems to got deleted or hidden; I created a new one: https://ciscocollabcustomer.ideas.aha.io/ideas/WXCUST-I-12926

**Comment by Joezanini** [comment]
Hello Team, I will bring this up with product. For now I will close this issue. Please follow associated aha for progress reports on feature request.
