### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by k-kov** [WebexCommunity/WebexPythonSDK#197]
I started to work with SDK and read docs on https://webexteamssdk.readthedocs.io/en/latest/user/quickstart.html

In Quickstart menu there are many links, first one ([sign-up for one here](https://webexteamssdk.readthedocs.io/en/latest/user/WebexTeams_)) is broken (404)

I got all I need but any other developers may have problem.

![Screenshot 2023-08-29 at 8 48 29 AM](https://github.com/WebexCommunity/WebexPythonSDK/assets/142822678/8ee96ee9-f48b-429b-b45a-6fca10f83d86)
![Screenshot 2023-08-29 at 8 46 43 AM](https://github.com/WebexCommunity/WebexPythonSDK/assets/142822678/9437c135-47ad-4758-98f1-819e0931a744)

**Comment by adamweeks** [comment]
Docs have been updated 😄
