### ISSUE TITLE
webexteamssdk broken in python >= v3.12

### ISSUE THREAD

**Issue by fredless** [WebexCommunity/WebexPythonSDK#200]
Related to older issue filing #139, this project imports `future` which relies on `imp` - the latter of which [has been removed as of v3.12](https://docs.python.org/3.12/whatsnew/3.12.html#imp) (and considering the problem `future` set out to solve, mildly ironic). See also PythonCharmers/python-future#625

**Comment by Joezanini** [comment]
I will be removing this dependency from the project. https://docs.python.org/3/reference/simple_stmts.html#future-statements
