### ISSUE TITLE
PEP8 requirement

### ISSUE THREAD

**Issue by Joezanini** [WebexCommunity/WebexPythonSDK#211]
There are a lot of files and lines that do not adhere to PEP8 as required based on the documentation. When testing, most tests fail because of this.

**Comment by cmlccie** [comment]
Yeah, it looks like the recent additions were not properly formatted or checked against `flake8`. To help resolve these errors and get the tests working again, I am going to use [ruff](https://docs.astral.sh/ruff/) to help with the formatting and get the `flake8` linting working again.

In v2, we'll re-tool to use `ruff` for formatting and linting.
