### ISSUE TITLE
Deploy PyPi version incorporating latest master branch fixes

### ISSUE THREAD

**Issue by algarbar** [WebexCommunity/WebexPythonSDK#229]
There are bug fixes in the WebexPythonSDK master branch which are missing in the install of the latest PyPi version of webexteamssdk (1.6.1). [Example](https://github.com/WebexCommunity/WebexPythonSDK/pull/188)

By deploying these revisions to PyPi accessible versions, it ensures the hard work this community has done is made readily available to users and reduces noise for known (and solved!) problems.

Thanks!

**Comment by Joezanini** [comment]
These items have been addressed and the PyPi version of webexteamssdk is now 1.7.

**Comment by algarbar** [comment]
@Joezanini - Awesome!! Update confirmed. Thank you.
