### ISSUE TITLE
 dependency issue | webexteamssdk 1.7 depends on PyJWT==1.7.1 

### ISSUE THREAD

**Issue by Loprock** [WebexCommunity/WebexPythonSDK#231]
I'm configuring my bot over Python and I'm using multiple chat platforms which require at least PyJWT>=2.4.0
the repo requires PyJWT 1.7.1.

can you update the version of PyJWT? or give me an alternative solution?

**Comment by adamweeks** [comment]
@Loprock PyJWT is updated in the 3.0 release

https://github.com/WebexCommunity/WebexPythonSDK/pull/234/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R45
