### ISSUE TITLE
[403] Forbidden with messages.list() when using bot token

### ISSUE THREAD

**Issue by wematta** [WebexCommunity/WebexPythonSDK#235]
We are getting [403] Forbidden with messages.list() when using bot token, it works with my personal token.  We are able to post messages in a room with messages.create() using the Bot token.

**Comment by Joezanini** [comment]
I will check with Developer support to see if this functionality is intentional for bots. Bots may. not have permissions to use that API.

**Comment by adamweeks** [comment]
Hey @wematta, according to the docs (and my personal testing) https://developer.webex.com/docs/api/v1/messages/list-messages API requires `mentionedPeople="me"` parameter:

> mentionedPeople
array
List messages with these people mentioned, by ID. Use me as a shorthand for the current API user. Only me or the person ID of the current user may be specified. Bots must include this parameter to list messages in group rooms (spaces).

**Comment by wematta** [comment]
Hello @adamweeks,  Thanks for your suggestions, I was able to get this to work now!
